version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: basic
    cap_add:
      - SYS_NICE
    ports:
      - "3308:3306"